apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-2
  namespace: default
  
spec:
  replicas: 3
  selector:
    matchLabels:
      run: web-2
  template:
    metadata:
      labels:
        run: web-2
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        imagePullPolicy: IfNotPresent
        name: web-2
        ports:
        - containerPort: 8080
          protocol: TCP
