apiVersion: v1
kind: Pod

metadata:
  name: projected-volume

spec:
  containers:
  - name: pv-container
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
    - name: busybox-pv-volume
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: busybox-pv-volume
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pswd
