apiVersion: v1
kind: PersistentVolume

metadata:
  name: my-volume
  labels:
    failure-domain.beta.kubernetes.io/zone: us-central1-c
    
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard 
  gcePersistentDisk:
    pdName: gke-gke-cluster-001-default-pool-9ce22aad-626s
