kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: pv-claim
  
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
