apiVersion: v1
kind: Pod

metadata:
  name: security-context-demo

spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    capabilities:
      add: ["NET_ADMIN", "SYS_TIME"]
    seccompProfile: 
      type: Localhost
      localhostProfile: <path of the file>
    seLinuxOptions:
      level: "<value>"
      role: "<value>"
      type: "<value>"
      user: "<value>"
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false 
