apiVersion: v1
kind: Pod

metadata:
  name: config-test-pod

spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "cat /etc/config/gameplay.beta1" ]
  volumeMounts:
  - name: config-volume
    mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: game-config
  restartPolicy: Never
